beta pages "Favorites", "My Posts" and "Messages" and corrected images
cmps-department/charity-ui pull request #21
Opened 2023-05-19 13:50 UTC by AnastasiiaMjlxy

2023-05-19 14:47 UTC, ArCheeq requested changes
Everything is good, update the branch with changes and fix the comments please

2023-05-19 14:47 UTC, ArCheeq commented on src/App.js
> +import MessagesPage from "./pages/MessagesPage";
in the updated code now use lazy loading instead of default import

2023-05-19 14:47 UTC, ArCheeq commented on src/App.js
> +          <Route path="/myPosts" element={<MyPostsPage/>} />
delete "/" symbol from path

2023-05-19 14:47 UTC, ArCheeq commented on src/pages/FavoritesPage.js
> +    <main className="container max-w-xl mx-auto my-15 px-4">
remove tag "main", now it is in the layout component

2023-05-19 14:47 UTC, ArCheeq commented on src/pages/MyPostsPage.js
> +    <main className="container max-w-xl mx-auto my-15 px-4 flex flex-wrap justify-between gap-[15px] mt-8">
same

2023-05-19 15:16 UTC, Misha999777 approved these changes
LGTM, except for formatting

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Done.js
> +          <p className="text-gray-700 text-xl text-left my-4">Збір від Володимира Андрєєва був закритий! Дякуємо кожному, за допомогу. Тепер Ви можете перейти та подивитися на звіт автора.</p>
Line is too long

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/MessagesList.js
> +
Remove this gap

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/MessagesList.js
> +
Remove this gap

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/MessagesList.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Issue.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Done.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/components/MyCard.js
> +  <div className="text-center mb-3 flex justify-between items-center">
Align, please

2023-05-19 15:16 UTC, Misha999777 commented on src/components/MyCard.js
> +
Remove this gap

2023-05-19 15:16 UTC, Misha999777 commented on src/components/MyCard.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Verified.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Views.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Warning.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/pages/FavoritesPage.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/pages/MessagesPage.js
> +
One empty line is enough here

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Issue.js
> +          <p className="text-gray-700 text-xl text-left my-4">Модератор: 012345</p>
Lines are too long

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Verified.js
> +          <p className="text-gray-700 text-xl text-left my-4">Модератор: 039355</p>
Lines are too long

2023-05-19 15:16 UTC, Misha999777 commented on src/components/messages/Views.js
> +          <p className="text-gray-700 text-xl text-left my-4">Ваше оголошення від 23.04.2023 переглянули 1 000 людей! Сподіваємось, що незабаром збір буде закрито.</p>
Line is too long

2023-05-20 08:29 UTC, ArCheeq approved these changes
Thanks for the corrections

2023-05-20 08:29 UTC, merged